### ISSUE TITLE
Request - Show only hit data

### ISSUE THREAD

**Issue by stevown** [LiangYuxuan/Details_ExplosiveOrbs#1]
Great plugin!

This is more a request than an issue, I couldn't figure out where to put requests. 

Would be nice to have a toggle, or an extra custom display available in the dropdown to hide "target" data; All I want to see is the hits. People are getting confused about how many splosions they are actually helping with - some folks cycle targets but don't actually hit them. 

I figured out how to do this in the core.lua (by editing Engine:GetDisplayText and Engine:FormatDisplayText) but I thought I'd see if you could make it optional.

![image](https://user-images.githubusercontent.com/73609191/114084132-0fde0d80-986d-11eb-9d63-5051e24af028.png)

**Comment by skittlezmb** [comment]
I also want this. Can you tell me more specifically what you change in the core.lua?
