### ISSUE TITLE
Error Core.lua

### ISSUE THREAD

**Issue by Hollicsh** [LiangYuxuan/Details_ExplosiveOrbs#24]
24x Details_ExplosiveOrbs\Core.lua:458: attempt to index a nil value
[string "@Details_ExplosiveOrbs\Core.lua"]:458: in function <Details_ExplosiveOrbs\Core.lua:449>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `MergeTrashCleanup'
[string "@Details\functions\mythicdungeon.lua"]:442: in function `BossDefeated'
[string "@Details\functions\mythicdungeon.lua"]:844: in function <Details\functions\mythicdungeon.lua:817>

Locals:
self = <table> {
 current = 12194
 SetDefaultModuleLibraries = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:367
 OnResetOverall = <function> defined @Details_ExplosiveOrbs\Core.lua:508
 overall = 12195
 Enable = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 OnDetailsEvent = <function> defined @Details_ExplosiveOrbs\Core.lua:535
 EnableModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:442
 eventFrames = <table> {
 }
 SecureHook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 orbID = 120651
 CustomDisplayOverall = <table> {
 }
 baseName = "Details_ExplosiveOrbs"
 RawHookScript = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:395
 debug = false
 OnInitialize = <function> defined @Details_ExplosiveOrbs\Core.lua:662
 hooks = <table> {
 }
 MergeCombat = <function> defined @Details_ExplosiveOrbs\Core.lua:405
 SetDefaultModulePrototype = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:409
 Disable = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:314
 plugin = <table> {
 }
 CustomDisplay = <table> {
 }
 name = "Details_ExplosiveOrbs"
 InstallPlugin = <function> defined @Details_ExplosiveOrbs\Core.lua:642
 IsEnabled = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 NewModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:235
 DisableModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:350
 RecordTarget = <function> defined @Details_ExplosiveOrbs\Core.lua:346
 MergeRemainingTrashAfterAllBossesDone = <function> defined @Details_ExplosiveOrbs\Core.lua:489
 LoadHooks = <function> defined @Details_ExplosiveOrbs\Core.lua:559
 MergeSegmentsOnEnd = <function> defined @Details_ExplosiveOrbs\Core.lua:421
 RegisterMessage = <function> defined @ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UnhookAll = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:477
 defaultModuleState = true
 IsHooked = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:493
 Debug = <function> defined @Details_ExplosiveOrbs\Core.lua:294
 CleanDiscardCombat = <function> defined @Details_ExplosiveOrbs\Core.lua:517
 IsModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SendMessage = <function> defined @ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 CheckAffix = <function> defined @Details_ExplosiveOrbs\Core.lua:388
 MergeTrashCleanup = <function> defined @Details_ExplosiveOrbs\Core.lua:449
 SetEnabledState = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @AddO

**Comment by LiangYuxuan** [comment]
What's the version of WoW, Details and Details_ExplosiveOrbs?

**Comment by Hollicsh** [comment]
WoW - 9.2.7 (45745)
Details! - DF.SL.Wrath.10136.146
Details_ExplosiveOrbs - v9.2.7

**Comment by LiangYuxuan** [comment]
It's weird because that line contains three vars which are not possible to be nil.
Next time you encounter this lua error, please try the following macro and reply with what it prints:
`/run print(Details and (Details.GetCombat and (Details:GetCombat(1) and Details:GetCombat(1).IsMythicDungeon or 'Combat1') or 'GetCombat') or 'Details')`

Thank you!

**Comment by LiangYuxuan** [comment]
Tested before explosive gone but failed to reproduce.

**Comment by Hollicsh** [comment]
Again ..

25x Details_ExplosiveOrbs\Core.lua:458: attempt to index a nil value
[string "@Details_ExplosiveOrbs\Core.lua"]:458: in function <Details_ExplosiveOrbs\Core.lua:449>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `MergeTrashCleanup'
[string "@Details\functions\mythicdungeon.lua"]:442: in function `BossDefeated'
[string "@Details\functions\mythicdungeon.lua"]:844: in function <Details\functions\mythicdungeon.lua:817>

Locals:
self = <table> {
 current = 12194
 SetDefaultModuleLibraries = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:367
 OnResetOverall = <function> defined @Details_ExplosiveOrbs\Core.lua:508
 overall = 12195
 Enable = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 OnDetailsEvent = <function> defined @Details_ExplosiveOrbs\Core.lua:535
 EnableModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:442
 eventFrames = <table> {
 }
 SecureHook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 orbID = 120651
 CustomDisplayOverall = <table> {
 }
 baseName = "Details_ExplosiveOrbs"
 RawHookScript = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:395
 debug = false
 OnInitialize = <function> defined @Details_ExplosiveOrbs\Core.lua:662
 hooks = <table> {
 }
 MergeCombat = <function> defined @Details_ExplosiveOrbs\Core.lua:405
 SetDefaultModulePrototype = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:409
 Disable = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:314
 plugin = <table> {
 }
 CustomDisplay = <table> {
 }
 name = "Details_ExplosiveOrbs"
 InstallPlugin = <function> defined @Details_ExplosiveOrbs\Core.lua:642
 IsEnabled = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 NewModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:235
 DisableModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:350
 RecordTarget = <function> defined @Details_ExplosiveOrbs\Core.lua:346
 MergeRemainingTrashAfterAllBossesDone = <function> defined @Details_ExplosiveOrbs\Core.lua:489
 LoadHooks = <function> defined @Details_ExplosiveOrbs\Core.lua:559
 MergeSegmentsOnEnd = <function> defined @Details_ExplosiveOrbs\Core.lua:421
 RegisterMessage = <function> defined @ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UnhookAll = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:477
 defaultModuleState = true
 IsHooked = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:493
 Debug = <function> defined @Details_ExplosiveOrbs\Core.lua:294
 CleanDiscardCombat = <function> defined @Details_ExplosiveOrbs\Core.lua:517
 IsModule = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SendMessage = <function> defined @ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 CheckAffix = <function> defined @Details_ExplosiveOrbs\Core.lua:388
 MergeTrashCleanup = <function> defined @Details_ExplosiveOrbs\Core.lua:449
 SetEnabledState = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @AddO
 
 
 **Macros: Combat1**
